
spring:
  application:
    name: Blogging platform
  config:
    import: file:.env[.properties]
  profiles:
    active: dev
  graphql:
    graphiql:
      enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enable: false

