spring:
  application:
    name: "Blogging platform"
  config:
    import: optional:file:.env[.properties]
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000      # 5 min
      connection-timeout: 30000 # 30s
      max-lifetime: 1800000     # 30 min
      pool-name: BlogDBPool

  jpa:
    hibernate:
      ddl-auto: update        # create / update / validate / none
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    com.amalitech.blogging_platform.config: DEBUG
    org.springframework.boot.actuate: TRACE
    org.springframework.boot.actuate.autoconfigure: TRACE
    org.springframework.boot.web.servlet.context: DEBUG
    org.springframework.context: DEBUG
    com.zaxxer.hikari: INFO


app:
  jwt:
    secret-key: ${JWT_SECRET}
    expire-after: 3600000 # 1 h (in millisec)
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-headers: ${CORS_ALLOWED_HEADERS}
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS}
  admin:
    email: ${SYSTEM_ADMIN_EMAIL}
    username: ${SYSTEM_ADMIN_USERNAME}
    password: ${SYSTEM_ADMIN_PASSWORD}
    first-name: ${SYSTEM_ADMIN_FIRSTNAME}
    last-name: ${SYSTEM_ADMIN_LASTNAME}



management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
