scrape_configs:
  - job_name: 'Blogging Platform '
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # Time to reload data
    static_configs:
      - targets: ['blogging-platform:8080']